### ISSUE TITLE
Create Search UI With Material UI

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/PDS.nasa.gov-Search#11]
Recreate the search UI in a new branch using Material UI

**Comment by jordanpadams** [comment]
Status: Working on updating the UI with material. Action for @tdddblog to restart the search server on pds-dev-el7

**Comment by jordanpadams** [comment]
@eddiesarevalo status: began updates on the old search ui, and set it up ability to swap themes, and documenting appropriately.

**Comment by tloubrieu-jpl** [comment]
Eddie is working on implementation of material design on search ui headers and footers. Once done, that will be easy to switch to the material design compliant inputs provided by Edward.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo will create a pull request.

**Comment by tloubrieu-jpl** [comment]
Pull request created.
