### ISSUE TITLE
ds-view returns inconsistent, usually wrong, results

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/PDS.nasa.gov-Search#13]
On https://pds.nasa.gov/datasearch/keyword-search/, enter "cassini iss".
Under "Type" on left, click "Bundle"
In the results, click either
"Bundle: ISS Observations from the Cassini Cruise to Saturn" or
"Bundle: ISS Observations from the Cassini Tour of the Saturn System" or
two lower results with "VIMS" instead of "ISS"
On the resulting page, the list of "TARGET"s usually does not complete, and refreshing that page later returns a shorter or longer list
![Screen Shot 2020-07-24 at 11 51 16](https://user-images.githubusercontent.com/56557532/88425315-0fb3e580-cda4-11ea-8d58-81f7afd5671f.jpg)

**Comment by rchenatjpl** [comment]
Something else maybe related is going on. The bundle.xml for Cassini VIMS Cruise references a bunch of targets, but not all show up in the search page. In the attachment, the left column shows Target_Identification/name from the bundle.xml. The middle column is title from the various context products. The right is the output results. So Beta Gruis / Betelgeuse and a few others are missing.

I think that's the wrong behavior. I'd suggest listing both with a pipe or slash separator, with the one from the context product first. Else, I'd pick one (probably the one from the context product) or the other. (shoot, the screen capture cut off the top line)
![Screen Shot 2020-07-25 at 11 10 22](https://user-images.githubusercontent.com/56557532/88463428-9382d600-ce67-11ea-9dda-a033d8c71cad.jpg)

**Comment by jordanpadams** [comment]
Email sent to SA Team to dry to address "Too many open files" error:

> Hello SA Team,
> 
> We are seeing an issue with one of our applications accessing our Solr index on both pds-gamma and pds-prod1. From the tomcat logs, it looks like it may be a file limit issue:
> 
> 29-Jul-2020 05:46:04.422 SEVERE [http-nio-8080-Acceptor-0] org.apache.tomcat.util.net.NioEndpoint$Acceptor.run Socket accept failed
>  java.io.IOException: Too many open files
> 
> Per the Solr recommendations, can we increase this number significantly to avoid this problem?
> 
> https://lucene.apache.org/solr/guide/7_3/taking-solr-to-production.html
> 
> 
> Thanks,
> Jordan
>

**Comment by jordanpadams** [comment]
After working with SAs to increase the number of possible open files, it appears this should be fixed-ish. it still fails on occasion, but only if you try to access the website quickly one after the other. this is probably something with Solr/OS/tomcat taking some time to close all the connections it is creating. I think we can call this good for now and see if it shows up again in the future.

https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Acassini_iss_saturn&version=1.0
