### ISSUE TITLE
Create App Bar Code Snippet

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/PDS.nasa.gov-Search#16]
Implement the app bar from Edward's Figma file and post the code on the PDS design system so that others can use the app bar.

**Comment by tloubrieu-jpl** [comment]
First version demonstrated by Eddie https://pds-dev2.jpl.nasa.gov/searchui/demo/

**Comment by jordanpadams** [comment]
@eddiesarevalo has this code been pushed somewhere in Github so we can close this ticket?

**Comment by tloubrieu-jpl** [comment]
Eddie should finish that today.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo worked on the accessibility since last Thursday. Should be ready by coming Thursday.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo did you find a way to handle the 'current node' highlight in the app bar ? That should be done in the user session is it ? @jordanpadams If Eddie does not have an easy solution for that we can create a new ticket as a feature request and close this one, what do you think ?
