### ISSUE TITLE
Develop initial draft of PDS Collection / Bundle Landing Page mock-ups

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS.nasa.gov-Search#19]
Develop landing page mock-ups for PDS4 Bundle and Collections based upon [these requirements](https://docs.google.com/spreadsheets/d/1bmXoDHr3uHvkUkkr9VX9zlZTiPWGG_wErCstmX-Jn3c/edit?usp=drive_web&ouid=110989165846091279020)

Additionally, using pages as examples to inform your decisions and borrowing functionality where reasonable from SBN web pages:

Example bundle:
* https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Acassini_iss_saturn&version=1.0
* https://sbnarchivedemo.psi.edu/?identifier=urn:nasa:pds:cassini_iss_saturn

Example collection:
* https://pds.nasa.gov/ds-view/pds/viewCollection.jsp?identifier=urn:nasa:pds:cassini_iss_saturn:data_raw 
* https://sbnarchivedemo.psi.edu/?dataset=urn:nasa:pds:cassini_iss_saturn:data_raw

**Comment by tloubrieu-jpl** [comment]
Eddie started that.

**Comment by jordanpadams** [comment]
ℹ️ Status: Working on figuring out what information is on current implementation and what needs to be added. Continuing to sift through the requirements.

**Comment by jordanpadams** [comment]
@eddiesarevalo status: continuing to work mock-ups, planning to have something to discuss on Thursday. @jordanpadams will setup a meeting to discuss details for Thursday.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo completed a mockup including new requirements from Jordan.

This will likely generate a new ticket for the coming milestone.

**Comment by tloubrieu-jpl** [comment]
Consider also the integration of search widgets for:
1) pds level search
2) node level search (with relevant search engines)

See example https://sbnarchivedemo.psi.edu/?identifier=urn:nasa:pds:context:target:planet.mars

**Comment by tloubrieu-jpl** [comment]
See also as an example for the landing page: https://www.seanoe.org/data/00642/75444/

**Comment by jordanpadams** [comment]
Here is another example: https://podaac.jpl.nasa.gov/dataset/CYGNSS_L1_CDR_V1.0

**Comment by eddiesarevalo** [comment]
Mockups before first iteration. Will create new version following new suggestions.
[https://app.zenhub.com/files/256052135/2a571f85-a249-4d45-a6c0-136353586f8e/download](https://app.zenhub.com/files/256052135/2a571f85-a249-4d45-a6c0-136353586f8e/download)

**Comment by tloubrieu-jpl** [comment]
@Eddie iterated on the first review.

We will discuss that in a meeting later this Thursday.

**Comment by eddiesarevalo** [comment]
-Rearrange the author and description information to be near the top. Will also move the citation lower.
-Change the collection and bundle information. The file representation isn't the right one.

[https://app.zenhub.com/files/256052135/b1f93504-2a8e-44c7-afa4-460b5872020e/download](https://app.zenhub.com/files/256052135/b1f93504-2a8e-44c7-afa4-460b5872020e/download)

**Comment by eddiesarevalo** [comment]
Created a new version. Used a different example of collection as the other one had errors in it. We can review next chance @tloubrieu-jpl and @jordanpadams get a chance.

[https://app.zenhub.com/files/256052135/22eac5da-001f-458f-a6ce-3271d620f842/download](https://app.zenhub.com/files/256052135/22eac5da-001f-458f-a6ce-3271d620f842/download)

Changes:
-Added button at the very top of the page that allows visitor to view data in original discipline node.
-Moved author and description information above the file directory structure. 
-Move the citation under the file directory structure.
-Changed fonts to be more realistic

**Comment by tloubrieu-jpl** [comment]
New iteration taken into account by Eddie. Edward is also providing inputs on that.

One iteration left is expected.

**Comment by tloubrieu-jpl** [comment]
A few more changes need to be done. We can review it during the next 'revamp' Thursday meeting.

**Comment by eddiesarevalo** [comment]
Added more changes in this version:
[https://app.zenhub.com/files/256052135/5036d9ff-9330-4d7e-8eda-fa40d65f09c5/download](https://app.zenhub.com/files/256052135/5036d9ff-9330-4d7e-8eda-fa40d65f09c5/download)

**Comment by eddiesarevalo** [comment]
Version from the last meeting with SBN-PSI
[https://app.zenhub.com/files/256052135/65b35988-2e5e-4098-93d8-a2cd72e7d4d8/download](https://app.zenhub.com/files/256052135/65b35988-2e5e-4098-93d8-a2cd72e7d4d8/download)

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo just a though that I had during you presentation for SBN (which was very clear and design choices were clearly motivated, congratulations !). For the large screen version, you said the general section will be extended by default (as-is show more is clicked compared to small screen version). I think we should make sure, as much as possible, that the view or browse data is still available without scrolling down.
