### ISSUE TITLE
Review search details / DOI page updates

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS.nasa.gov-Search#26]
https://github.com/NASA-PDS/PDS.nasa.gov-Search/issues/20#issuecomment-715596383

**Comment by edwardbarraza** [comment]
Here is some crit for what is here

Is this supposed to adhere to our dark theme that we defined?
I think removing 'relevant tags' is ok. They are removed when adjusted for mobile, so I think it ok to remove this all together
Regarding the right-hand container (other versions, PDS3 Versions, etc.), is this something we can potentially push back in to an accordion header, much like 'show more'? Why do we have this in its own container (what makes it so special?)
Also, no good reason to have each version to be contained in their own card. We can just contain them in to one accordion or module container as you see in the mockup I've attached
I am confused as to why we use 'bundle' and 'dataset' when concerning Bundles. Are they the same thing? Or are we nudging user to browse the collection with the button? I am not sure what the distinction is.
We don't have that sized button defined in the design system - it is a bit excessive
We have icons defined in the design system - I have swapped for our flat 'folder' icon.
Here is a mockup of what it should look like in the theme:

<img width="1280" alt="DOI Landing Page (L Breakpoint)" src="https://user-images.githubusercontent.com/26258411/98039585-c4ae6300-1dd3-11eb-9649-75d9c1748d6e.png">
