### ISSUE TITLE
Initial investigation for Search UI utilizing PDS API and identify new API user stories

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS.nasa.gov-Search#33]
See #31 for details.

- [x] identify gaps in the PDS API needs to support the PDS API - @eddiesarevalo 
- [x] develop new user stories based upon those findings. - @tloubrieu-jpl

**Comment by jordanpadams** [comment]
Email traffic between @eddiesarevalo and @tloubrieu-jpl regarding issues with the search API for completing this implementation for the time being.

[search_api_upgrades_for_search_ui.pdf](https://github.com/NASA-PDS/PDS.nasa.gov-Search/files/6750814/search_api_upgrades_for_search_ui.pdf)

**Comment by eddiesarevalo** [comment]
_--From an email. @tloubrieu-jpl's response is bolded.--_

1) Is the new search API going to continue using natural language processing? 
**Yes later**

2) Is a general search of the PDS going to be performed using the products API? [https://nasa-pds.github.io/pds-api/#tag/products](https://nasa-pds.github.io/pds-api/#tag/products )
**Yes**

3) When I try to use the products API  [https://pds-gamma.jpl.nasa.gov/api/products?start=0&limit=100&q=mars](https://pds-gamma.jpl.nasa.gov/api/products?start=0&limit=100&q=mars ) to search for example 'mars' I get a 'This page isn't working' error:
![imageerror1.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/832bb53c-c293-40f4-be05-38b28f145c11)
**There is a query syntax which does not handle text search yet, but property eq value 
There is a ticket for that https://github.com/NASA-PDS/registry-api-service/issues/5**

4) Are we going to support faceting? In the API documentation there is a query parameter for field but how do we add values for those fields?
![imageerror2.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/3f066a4f-8d81-46ec-b6ed-aced34b1fd53)
**Yes we need to create ticket**

5) In the current UI we have a filter button between data and documentation. Is this still going to exist or will we only differentiate between bundle and collections?
![imageerror3.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/e89ed52b-f507-42db-84d9-31d72ea70f2c)
@jordanpadams ?

_--End email--_

**Comment by jordanpadams** [comment]
@eddiesarevalo I attached a PDF above, but this works too. Thanks

**Comment by tloubrieu-jpl** [comment]
Here are the follow-on tickets which will eventually answer the current ticket questions:

1) Is the new search API going to continue using natural language processing? 

Yes later, see ticket https://github.com/NASA-PDS/registry-api/issues/570


2) Is a general search of the PDS going to be performed using the products API? https://nasa-pds.github.io/pds-api/#tag/products 

Yes

3) When I try to use the products API  https://pds-gamma.jpl.nasa.gov/api/products?start=0&limit=100&q=mars to search for example 'mars' I get a 'This page isn't working' error:

There is a query syntax which does not handle text search yet, but property eq value

There is a ticket for that:
https://github.com/NASA-PDS/pds-api/issues/84


4) Are we going to support faceting? In the API documentation there is a query parameter for field but how do we add values for those fields?

Yes, see ticket https://github.com/NASA-PDS/registry-api/issues/284


5) In the current UI we have a filter button between data and documentation. Is this still going to exist or will we only differentiate between bundle and collections?

Yes, see ticket:
https://github.com/NASA-PDS/registry-api/issues/461
