### ISSUE TITLE
Scope Context Browser integration approach and schedule

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds.nasa.gov-search#4]

**Comment by eddiesarevalo** [comment]
The context browsers are at:
https://github.com/sbn-psi/archive-viewer
and
https://github.com/sbn-psi/archive-viewer/tree/master/src/css

**Comment by jordanpadams** [comment]
Will take about a month.

Per 2020-05-07 planning meeting, decided to:
* fork this repo into NASA-PDS
* create new repo for PDS Skin
* Have pds.nasa.gov-search and context browser use PDS Skin with git submodules
