### ISSUE TITLE
Research Search Interface SEO

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/PDS.nasa.gov-Search#43]
## 💪 Motivation
Research wordpress SEO and embedded react SEO.
In other words how to make it so that search engines can see the search box and know this is the main search page.

## 📖 Additional Details
Normally search engines read wordpress easily. Client side react is also read normally although it takes longer for search engines to index. Would they know how to index react inside wordpress?

## ⚖️ Acceptance Criteria
Do a report of the findings.

## ⚙️ Engineering Details
Nasa HDS Wordpress has an seo measuring plugin in. This might not check any embedded apps. Maybe there is a way to run an open source indexer on our page to get an estimate of SEO results.

**Comment by eddiesarevalo** [comment]
Some quick notes on how to keep the SEO for wordpress and react working together.

Google has increased capability from the past. It has made an effort to read react and it already reads wordpress really well. it will be able to read react inside wordpress but there are some things to keep in mind on top of the normal SEO items

Avoiding hash router. Hashed URLs such as /#/about will be ignored by google. This means we can’t use hash router. We will need to use browser router or history router. Which means we will have to build specifically for a deployment.

Load times must be kept short. As long as the page is loaded quickly enough then google can scan the page and read all the contents.

Fix router issues to prevent 404s. Or to make sure to deal with 404s. The router will have to deal with 404s so that errors aren't detected by google.

Use `<a href>` tags instead of <button> or <div>. Google needs to be allowed to index links. Custom tags are often used in react but extra care is needed to make sure `<a href>` tags are generated in the HTML

Avoid lazy loading important HTML. Anything lazy loaded will probably be missed by google.

Make sure the wordpress page contains the details for the search page. Wordpress will be detected first so the wordpress page needs to have all the metadata, not the react app.

Being Mobile friendly greatly increases SEO. Google is mobile-first so will attempt to index through a mobile browser first. Both our wordpress and react will need to be mobile friendly.

Allow a sitselinks search box using search : https://developers.google.com/search/docs/advanced/structured-data/sitelinks-searchbox This will allow a search box for our app to appear in google results.

Tests on indexing can be run through the Rich Results Test https://support.google.com/webmasters/answer/7445569

**Comment by tloubrieu-jpl** [comment]
Thanks @eddiesarevalo I wil close this ticket. I pasted your comment in the wds-react wiki https://github.com/NASA-PDS/wds-react/wiki/SEO-for-wordpress-and-react

wds-wordpress does not have a wiki because it is private I guess.
