### ISSUE TITLE
Create Search Bar With PDS Styles

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/PDS.nasa.gov-Search#45]
## 💪 Motivation
Create the PDS search bar so that search text can be entered. The search bar should be styled to the PDSWDS

## 📖 Additional Details
All search engines need an input form. This is it. The search bar will need the PDS WDS styles so this ticket includes creating those styles. 

## ⚖️ Acceptance Criteria
We will have a search bar. It will be styled to according to the PDS WDS.

## ⚙️ Engineering Details
The search box will send a call to the API containing the encoded search text.
We will probably use material ui for the accesibility and then create and add a PDS theme on top of that.

**Comment by jordanpadams** [comment]
@eddiesarevalo status: base theme created and added to app. going through and adding styling per the design docs HDS

up next: update theme to better reflect details in design docs

**Comment by eddiesarevalo** [comment]
Text field:
![Screen Shot 2022-11-01 at 2.00.34 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/53a9a377-39fb-4441-ab8b-ceebb17a302a)

From the design:![Screen Shot 2022-11-01 at 2.00.48 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/6ab9abb2-7f8b-42aa-8931-cd1786bd69ee)
