### ISSUE TITLE
Integrate SBN Context Browser to sync look-and-feel with current search UI

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS.nasa.gov-Search#5]

**Comment by jordanpadams** [comment]
June schedule status: Delayed due to dependency on https://github.com/NASA-PDS/PDS.nasa.gov-UX/issues/7

**Comment by mdrum** [comment]
I'm interested in seeing what we can do on our end to help this along. I see that the plan is now to use Material UI #11. Would the eventual hope be that we use the same look and feel on the context browser? I'd be happy to jump on a call to hash out how we could go about this, and what I can contribute to that.

On another note: have there been any discussions about how the context browser could be integrated & deployed under the pds.nasa.gov domain? We still are just hosting it at a temporary "sbnarchivedemo" subdomain here at PSI and I'd like to move it to a permanent home. If moving the deployment onto your servers, or routed through your domain, isn't technically/politically possible, I'd like to figure out an alternate plan.

**Comment by jordanpadams** [comment]
@mdrum sorry for just seeing this. we for sure plan on getting Material UI integrated with our new search interface and deployed alongside our app. Eddie is working to document porting a React app to use Material UI. once he wraps that up, we would love some help from the SBN team to test out and improve that documentation when trying to port the Context Browser. i restarted the monthly dev telecons beginning next Tuesday, so hopefully we can kickstart this during that discussion.

**Comment by jordanpadams** [comment]
July Schedule Status: Work on this task has been delayed and expanded due to its incorporation into the larger PDS UX effort. Additional sub-tasks to be added to the scope in the next week or 2, which will extend this effort through the end of the Build 11.0 development lifecycle.

**Comment by jordanpadams** [comment]
August Schedule Status: Awaiting for completion of Web Design System. Delay does not impact build delivery.

**Comment by jordanpadams** [comment]
August Schedule Status: On-track. End date pushed out two weeks. No affect on delivery to I&T.
